version: "3.7"

services:
  phoenix:
    build:
      context: .
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: postgres
      INVOICING_STORAGE_DATA_PATH: /invoicing_storage
      INVOICING_JOKEN_SECRET: very-secret-secret
    volumes:
      - invoicing:/invoicing_storage
    ports:
      - "6969:6969"
    depends_on:
      - postgres

  # DB for backend
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx-reverse-proxy:
    image: doxychainorg/nginx-reverse-proxy:latest
    environment:
      APPLICATION_URL: phoenix:6969
    ports:
      - "90:80"
    depends_on:
      - phoenix 
volumes:
  invoicing:
  pgdata:
