name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest 
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.10.2'
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          path: |
            deps
            _builds
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-v1
      - name: Setup
        run: |
          sudo apt update
          sudo apt install xvfb libfontconfig wkhtmltopdf
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      - name: DB migration
        run: MIX_ENV=test mix ecto.migrate --migrations-path priv/postgres/migrations
      - name: Test
        run: mix test 
      - name: Linter
        run: mix format --check-formatted
