name: CI

on: [push, pull_request]


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt update
        sudo apt install xvfb libfontconfig wkhtmltopdf
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
    - name: Linter
      run: mix format --check-fromatted
    - name: Test
      run: mix test
    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        path: |
          deps
          _builds
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
